# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YugiCards' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YugiCards
pod "Alamofire"
pod "SDWebImage"
pod "SnapKit"

  target 'YugiCardsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YugiCardsUITests' do
    # Pods for testing
  end

end
