# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyYugiOhCards' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyYugiOhCards
pod "Alamofire"
pod "SDWebImage"
pod "SnapKit"

  target 'MyYugiOhCardsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyYugiOhCardsUITests' do
    # Pods for testing
  end

end
