# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoviesSky' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoviesSky
pod "Alamofire"
pod "SDWebImage"
pod "SnapKit"

  target 'MoviesSkyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoviesSkyUITests' do
    # Pods for testing
  end

end
