# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PokemonViewCodeAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokemonViewCodeAPI
pod "Alamofire"
pod "SDWebImage"
pod "SnapKit"

  target 'PokemonViewCodeAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PokemonViewCodeAPIUITests' do
    # Pods for testing
  end

end
